dist: trusty
language: nix
script:
- git clone https://github.com/holochain/holochain-rust.git
- ls
- nix-shell --run 'npm run test && npm run build' ./holochain-rust/default.nix
- PACKAGE_NAME=$(node -p -e "require('./package.json').name")
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- cd dna
- ls
- zip -r $PACKAGE_NAME-$PACKAGE_VERSION.zip *
