[[agents]]
  id = "test_agent1"
  name = "Agent 1"
  public_address = "HcSCJbpm8CZparb6f5iEKKRv4Te4op93q6ESMRuDtwp9abbzV8zYTF7EKqqw9ei"
  keystore_file = "./agent1.keystore"

[[dnas]]
  id = "personas_profiles"
  file = "dna/personas-profiles-agent1.dna.json"
  hash = "QmYpd9Mevcf6bYB8PMsbFjyspAfFJnuFJaHVvTKhi1ySNS"


[[instances]]
  id = "personas-profiles"
  dna = "personas_profiles"
  agent = "test_agent1"
[instances.logger]
  type = "simple"
  file = "app_spec.log"
[instances.storage]
  type = "memory"
  path = "tmp-storage"


[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 5401
[[interfaces.instances]]
  id = "personas-profiles"

# -----------  UI  -----------

# [[ui_bundles]]
#   id = "main"
#   root_dir = "./ui"
#   hash = "Qm000"
#
# [[ui_interfaces]]
#   id = "ui-interface"
#   bundle = "main"
#   port = 3000
#   dna_interface = "websocket_interface"
