

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "sandwich--------------------------------------------------------------------------AAAEqzh28L"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent3"
name = "HoloTester3"
public_address = "croissant-------------------------------------------------------------------------AAAEuHzxV4"
key_file = "holo_tester.key"




[[dnas]]
id = "personas_profiles"
file = "dna/holo-vault.hcpkg"
hash = "Qm328wyq38924y"


[[instances]]
id = "holo-vault"
dna = "personas_profiles"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"



[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "holo-vault"


# ==========================
# =           UI           =
# ==========================

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 4001
dna_interface = "websocket_interface"

# ======  End of UI  =======


