

# generate a new keystore using hc keygen or use an existing keystore
# copy the public_address and path to the keystore into the [[agents]] section
# Give yourself an alpha-numeric id with no spaces (_ is ok)
# Enter your name
[[agents]]
id = "AgentID update the agent property in [[instances]]"
name = "Your agent name here"
public_address = "public addess"
keystore_file = "path/to/keystore"


[[dnas]]
id = "personas_profiles"
file = "dna/personas-profiles.dna.json"
hash = "Qm328wyq38924y"


[[instances]]
id = "personas-profiles"
dna = "personas_profiles"
agent = "same as id in [[agents]] section above"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "personas-profiles"

# -----------  UI  -----------

# [[ui_bundles]]
# id = "main"
# root_dir = "./ui"
# hash = "Qm000"
#
# [[ui_interfaces]]
# id = "ui-interface"
# bundle = "main"
# port = 3000
# dna_interface = "websocket_interface"
